default_context:
  project_name: 'fastapi-full-stack'
  project_slug: 'fastapi-full-stack'
  domain_main: 'fastapi-full-stack.com'
  domain_staging: 'stag.fastapi-full-stack.com'
  docker_swarm_stack_name_main: 'fastapi-full-stack-com'
  docker_swarm_stack_name_staging: 'stag-fastapi-full-stack-com'
  secret_key: '251e118525a760f81cc1908404f0590d3fed503d1fa8ae8a5cf5c50ea9c74b13'
  first_superuser: 'admin@admin.com'
  first_superuser_password: 'hogemoge'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.fastapi-full-stack.com", "https://stag.fastapi-full-stack.com", "https://fastapi-full-stack.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fastapi-full-stack.com'
  postgres_password: 'postgres'
  pgadmin_default_user: 'admin@admin.com'
  pgadmin_default_user_password: 'hogemoge'
  traefik_constraint_tag: 'fastapi-full-stack.com'
  traefik_constraint_tag_staging: 'stag.fastapi-full-stack.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:hogemoge'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
